version: "3.8"
services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./server/src/API/treasurehunt.db:/app/treasurehunt.db
      - ./server/ssl:/app/ssl

  frontend:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://localhost:5000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mssql-data:
